[package]
name = "csrf-token"
version = "0.1.0"
authors = ["Yusuke Yoshimoto <y.yoshimoto@f-s-r.jp>"]
publish = false

[dependencies]
chrono = "0.4.6"
rand = "0.5.5"
rust-crypto = "0.2.36"
byteorder = "1.2.6"
failure = "0.1.3"

[dev-dependencies]
base64 = "0.10.0"
lazy_static = "1.2.0"
