[package]
name = "csrf-token"
version = "0.2.2"
authors = ["Yusuke Yoshimoto <y.yoshimoto@f-s-r.jp>"]
publish = false

[dependencies]
chrono = "0.4"
rand = "0.5"
byteorder = "1.2"
thiserror = "1.0"
hmac = "0.10"
sha2 = "0.9"


